apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: gestion-notes
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "gestion_notes"
  DB_USERNAME: "root"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost:30080"
  FRONTEND_URL: "http://localhost:30080"