apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: gestion-notes
data:
  # Configuration Laravel
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "gestion_notes"
  
  # Configuration Frontend
  VITE_API_URL: "/api"
  VITE_APP_NAME: "Gestion Notes"