apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gestion-notes
type: Opaque
data:
  # Base64 encoded values
  DB_USERNAME: bGFyYXZlbA==  # laravel
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  MYSQL_ROOT_PASSWORD: cm9vdA==  # root
  APP_KEY: YmFzZTY0OmMvVS81aXJ0QmIrSVA4TWZHdCtlQXlScnJJcGcvV3hpVi9nSENCeVVPR3M9