apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: gestion-notes
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==     # "root" encod√© en base64
  MYSQL_DATABASE: Z2VzdGlvbl9ub3RlcyA=  # "gestion_notes"
